version: '3.8'

services:
  bot-slack:
    image: ${CI_REGISTRY_IMAGE}/bot-slack:${IMAGE_TAG:-latest}
    container_name: bot-slack
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.main
      - PYTHONPATH=/app
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
      - ../reports:/app/reports
      - ../data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: bot-slack-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates if needed
    depends_on:
      - bot-slack
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
  reports: