version: '3.8'

services:
  bot-slack:
    build: .
    container_name: bot-slack-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker operations
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bot-network

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: bot-slack-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates if needed
    depends_on:
      - bot-slack
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
  reports: